{{- $fullName := include "minio.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
    {{- if .Values.karvdash.enabled }}
    karvdash-no-auth: "true"
    {{- end }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  rules:
  - host: {{ .Values.karvdash.hostname | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $fullName }}
            port:
              number: 9000
