apiVersion: v1
kind: Service
metadata:
  name: {{ include "pgadmin.fullname" . }}
  labels:
    {{- include "pgadmin.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    {{- include "pgadmin.selectorLabels" . | nindent 4 }}
