apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx.fullname" . }}-config
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen       80;
        server_name  localhost;
        location / {
            root   {{ .Values.folder }};
            index  index.html index.htm;
        }
    }
