apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx.fullname" . }}
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    {{- include "nginx.selectorLabels" . | nindent 4 }}
