apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  admin-password: {{ default "admin" .Values.karvdash.adminPassword | b64enc }}
  django-secret: {{ default (randAlphaNum 50) .Values.karvdash.djangoSecret | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-webhook
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
---
apiVersion: v1
kind: Secret
metadata:
  name: karvdash-vouch
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
