apiVersion: v1
kind: Service
metadata:
  name: {{ include "filebrowser.fullname" . }}
  labels:
    {{- include "filebrowser.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: filebrowser
  selector:
    {{- include "filebrowser.selectorLabels" . | nindent 4 }}
