{{- $fullName := include "nginx.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "nginx.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nginx.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: nginx:1.21.6-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: {{ $fullName }}-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: {{ $fullName }}-config-volume
        configMap:
          name: {{ $fullName }}-config
          defaultMode: 0644
