apiVersion: v1
kind: Service
metadata:
  name: {{ include "ubuntu-lxde.fullname" . }}
  labels:
    {{- include "ubuntu-lxde.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    {{- include "ubuntu-lxde.selectorLabels" . | nindent 4 }}
