apiVersion: v1
kind: Service
metadata:
  name: {{ include "ubuntu.fullname" . }}
  labels:
    {{- include "ubuntu.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "ubuntu.selectorLabels" . | nindent 4 }}
  clusterIP: None
