apiVersion: com.ie.ibm.hpsys/v1alpha1
kind: Dataset
metadata:
  name: {{ include "s3-local.fullname" . }}
  labels:
    {{- include "s3-local.labels" . | nindent 4 }}
spec:
  local:
    type: "COS"
    endpoint: "http://{{ .Values.minio }}.{{ .Release.Namespace }}.svc:9000"
    accessKeyID: {{ .Values.accessKeyID }}
    secretAccessKey: {{ .Values.secretAccessKey }}
    bucket: {{ .Values.bucket }}
    region: ""
