apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubebox.fullname" . }}
  labels:
    {{- include "kubebox.labels" . | nindent 4 }}
    {{- if .Values.karvdash.enabled }}
    karvdash-no-datasets: "true"
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "kubebox.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kubebox.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: astefanutti/kubebox:0.9.0-server
        ports:
        - containerPort: 8080
