apiVersion: com.ie.ibm.hpsys/v1alpha1
kind: Dataset
metadata:
  name: {{ include "archive.fullname" . }}
  labels:
    {{- include "archive.labels" . | nindent 4 }}
spec:
  local:
    type: "ARCHIVE"
    url: {{ .Values.archiveURL }}
    format: "application/x-tar"
