apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "filebrowser.fullname" . }}-config
  labels:
    {{- include "filebrowser.labels" . | nindent 4 }}
data:
  filebrowser.json: |
    {
      "port": 80,
      "baseURL": "",
      "address": "",
      "log": "stdout",
      "database": "/database.db",
      "root": "{{ .Values.folder }}"
    }
