apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 9092
    name: broker
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
