apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-kubernetes.fullname" . }}
  labels:
    {{- include "hello-kubernetes.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "hello-kubernetes.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hello-kubernetes.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: carvicsforth/hello-kubernetes:1.10.1
        ports:
        - containerPort: 8080
        env:
        {{- if .Values.message }}
        - name: MESSAGE
          value: "{{ .Values.message }}"
        {{- end }}
