apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-kubernetes.fullname" . }}
  labels:
    {{- include "hello-kubernetes.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    {{- include "hello-kubernetes.selectorLabels" . | nindent 4 }}
