apiVersion: v2
name: karvdash
description: Karvdash provides a complete software stack for performing data science on Kubernetes
type: application
version: 0.0.0
kubeVersion: ">= 1.19.0"
sources:
- https://github.com/CARV-ICS-FORTH/karvdash
