apiVersion: v1
kind: Service
metadata:
  name: {{ include "zookeeper.fullname" . }}
  labels:
    {{- include "zookeeper.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 2181
    name: client
  selector:
    {{- include "zookeeper.selectorLabels" . | nindent 4 }}
