apiVersion: com.ie.ibm.hpsys/v1alpha1
kind: Dataset
metadata:
  name: {{ include "s3-remote.fullname" . }}
  labels:
    {{- include "s3-remote.labels" . | nindent 4 }}
spec:
  local:
    type: "COS"
    endpoint: "{{ .Values.endpoint }}"
    accessKeyID: {{ .Values.accessKeyID }}
    secretAccessKey: {{ .Values.secretAccessKey }}
    bucket: {{ .Values.bucket }}
    region: {{ .Values.region }}
