apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-webhook
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  secretName: {{ .Release.Name }}-webhook
  duration: 87600h
  commonName: {{ .Release.Name }}.{{ .Release.Namespace }}.svc
  dnsNames:
  - {{ .Release.Name }}.{{ .Release.Namespace }}.svc
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: {{ .Release.Name }}-selfsigned
