apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: maintenance
            image: bitnami/kubectl:1.22.4
            command: ["/bin/bash", "-c"]
            args:
            - POD_NAME=$(kubectl get pods -l app={{ .Release.Name }} -o=jsonpath='{.items[0].metadata.name}');
              kubectl exec $POD_NAME -c knot -- python manage.py deleteexpireduploads;
              kubectl exec $POD_NAME -c knot -- python manage.py deleteexpiredmessages;
              sleep 120
          restartPolicy: OnFailure
