{{- $ingressURL := (required "You must set knot.ingressURL to the ingress URL used" .Values.knot.ingressURL) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
    {{- if eq ($ingressURL | urlParse).scheme "https" }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    {{- end }}
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
spec:
  rules:
  - host: {{ (split ":" ($ingressURL | urlParse).host)._0 }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: 80
  - host: vouch.{{ (split ":" ($ingressURL | urlParse).host)._0 }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: 9090
