apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  DJANGO_SECRET: {{ default (randAlphaNum 50) .Values.knot.djangoSecret | b64enc }}
  KNOT_ADMIN_PASSWORD: {{ default "admin" .Values.knot.adminPassword | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-webhook
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-oauth-vouch
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
