# filebrowser.template.yaml

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: $NAME
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  rules:
  - host: $HOSTNAME
    http:
      paths:
      - backend:
          serviceName: $NAME
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: $NAME
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: filebrowser
  selector:
    app: $NAME
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebrowser-config
data:
  filebrowser.json: |
    {
      "port": 80,
      "baseURL": "",
      "address": "",
      "log": "stdout",
      "database": "/database.db",
      "root": "${FOLDER}"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $NAME
  template:
    metadata:
      labels:
        app: $NAME
    spec:
      containers:
      - name: $NAME
        image: filebrowser/filebrowser:v2.9.0
        ports:
        - containerPort: 80
        args: ["--noauth"]
        volumeMounts:
        - name: filebrowser-config-volume
          mountPath: /.filebrowser.json
          subPath: filebrowser.json
      volumes:
      - name: filebrowser-config-volume
        configMap:
          name: filebrowser-config
          defaultMode: 0644
---
kind: Template
name: File Browser
description: Frontend for viewing folder contents
variables:
- name: NAME
  default: filebrowser
- name: HOSTNAME
  default: filebrowser.example.com
- name: FOLDER
  default: /private
  help: Folder to browse
