# hello-kubernetes.template.yaml

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: $NAME
spec:
  rules:
  - host: $HOSTNAME
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: $NAME
            port:
              number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: $NAME
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    app: $NAME
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $NAME
  template:
    metadata:
      labels:
        app: $NAME
    spec:
      containers:
      - name: $NAME
        image: paulbouwer/hello-kubernetes:1.5
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: $MESSAGE
---
kind: Template
name: Hello Kubernetes
description: Show a message in a web page
variables:
- name: NAME
  default: hello-kubernetes
- name: HOSTNAME
  default: hello-kubernetes.example.com
- name: MESSAGE
  default: I just deployed this on Kubernetes!
  help: Message to display
