# kafka.template.yaml

apiVersion: v1
kind: Service
metadata:
  name: $NAME
spec:
  type: ClusterIP
  ports:
  - port: 9092
    name: kafka
  - port: 2181
    name: zeppelin
  selector:
    app: $NAME
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: start-scripts
data:
  start-zookeeper.sh: |
    #!/bin/bash -x
    /opt/bitnami/scripts/zookeeper/setup.sh
    mkdir -p ${REMOTE}/.zookeeper/data
    chown zookeeper:zookeeper ${REMOTE}/.zookeeper/data
    sed -i 's|dataDir=.*|dataDir=${REMOTE}/.zookeeper/data|' /opt/bitnami/zookeeper/conf/zoo.cfg
    /opt/bitnami/scripts/zookeeper/run.sh
  start-kafka.sh: |
    #!/bin/bash -x
    /opt/bitnami/scripts/kafka/setup.sh
    mkdir -p ${REMOTE}/.kafka/data
    chown kafka:kafka ${REMOTE}/.kafka/data
    sed -i 's|log.dirs=.*|log.dirs=${REMOTE}/.kafka/data|' /opt/bitnami/kafka/config/server.properties
    /opt/bitnami/scripts/kafka/run.sh
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $NAME
  template:
    metadata:
      labels:
        app: $NAME
    spec:
      containers:
      - name: kafka
        image: bitnami/kafka:2.5.0
        args: ["/start.sh"]
        ports:
        - containerPort: 9092
        securityContext:
          runAsUser: 0
        env:
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: localhost:2181
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: PLAINTEXT://${NAME}:9092
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        volumeMounts:
        - name: start-scripts-volume
          mountPath: /start.sh
          subPath: start-kafka.sh
      - name: zookeeper
        image: bitnami/zookeeper:3.6.1
        args: ["/start.sh"]
        ports:
        - containerPort: 2181
        securityContext:
          runAsUser: 0
        env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
        volumeMounts:
        - name: start-scripts-volume
          mountPath: /start.sh
          subPath: start-zookeeper.sh
      volumes:
      - name: start-scripts-volume
        configMap:
          name: start-scripts
          defaultMode: 0777
---
kind: Template
name: Kafka
description: Streaming platform
singleton: yes
variables:
- name: NAME
  default: kafka
- name: HOSTNAME
  default: kafka.example.com
- name: REMOTE
  default: /remote
