# postgresql.template.yaml

apiVersion: v1
kind: Service
metadata:
  name: $NAME
spec:
  type: ClusterIP
  ports:
  - port: 5432
  selector:
    app: $NAME
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $NAME
  template:
    metadata:
      labels:
        app: $NAME
    spec:
      containers:
      - name: $NAME
        image: postgres:${VERSION}
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: ${PASSWORD}
        - name: PGDATA
          value: ${PRIVATE_DIR}/.postgresql/data
---
kind: Template
name: PostgreSQL
description: Database server
singleton: yes
datasets: no
variables:
- name: NAME
  default: postgresql
- name: HOSTNAME
  default: postgresql.example.com
- name: PRIVATE_DIR
  default: /private
- name: VERSION
  default: 12.3
  help: PostgreSQL version
- name: PASSWORD
  default: postgres
  help: Password for postgres user
