# tensorboard.template.yaml

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: $NAME
spec:
  rules:
  - host: $HOSTNAME
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: $NAME
            port:
              number: 6006
---
apiVersion: v1
kind: Service
metadata:
  name: $NAME
spec:
  type: ClusterIP
  ports:
  - port: 6006
    name: tensorboard
  selector:
    app: $NAME
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $NAME
  template:
    metadata:
      labels:
        app: $NAME
    spec:
      containers:
      - name: $NAME
        image: tensorflow/tensorflow:2.3.2
        ports:
        - containerPort: 6006
        command:
        - bash
        - -c
        - |
          mkdir -p ${LOGDIR} && \
          tensorboard --logdir ${LOGDIR} --bind_all serve
---
kind: Template
name: TensorBoard
description: Visualization toolkit for TensorFlow
variables:
- name: NAME
  default: tensorboard
- name: HOSTNAME
  default: tensorboard.example.com
- name: LOGDIR
  default: /private/tf/logs
  help: Log directory
