apiVersion: com.ie.ibm.hpsys/v1alpha1
kind: Dataset
metadata:
  name: {{ include "h3-local.fullname" . }}
  labels:
    {{- include "h3-local.labels" . | nindent 4 }}
spec:
  local:
    type: "H3"
    storageUri: "redis://{{ .Values.redis }}.{{ .Release.Namespace }}.svc"
    bucket: {{ .Values.bucket }}
