{{- $fullName := include "rabbitmq.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
    {{- if .Values.knot.enabled }}
    knot-no-auth: "true"
    {{- end }}
spec:
  rules:
  - host: {{ .Values.knot.hostname | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $fullName }}
            port:
              number: 15672
