apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 6379
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
