apiVersion: v1
kind: Service
metadata:
  name: {{ include "tensorboard.fullname" . }}
  labels:
    {{- include "tensorboard.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 6006
  selector:
    {{- include "tensorboard.selectorLabels" . | nindent 4 }}
