
name: Publish Karvdash client
on:
  workflow_dispatch:
  push:
    tags:
      - 'client/v*'
jobs:
  docs:
    name: Publish package
    runs-on: ubuntu-latest
    container: python:3.7.9-slim
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build client
        run: |
          (cd client && python setup.py sdist)
      - name: Publish package to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          packages_dir: client/dist
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: client/dist
