name: Publish Knot
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
jobs:
  docs:
    name: Publish docs
    runs-on: ubuntu-latest
    container: python:3.12.9-slim
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y git
      - name: Build docs
        run: |
          pip install mkdocs==1.6.1 mkdocs-include-markdown-plugin==7.1.4
          mkdocs build
      - name: Push docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
          destination_dir: docs
  image:
    name: Publish image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: amd64,arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        run: |
          make container-push
  chart:
    name: Publish chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set version
        run: |
          VERSION=$(cat ./VERSION)
          echo "VERSION=${VERSION##*v}" >> $GITHUB_ENV
      - name: Publish chart to GitHub Pages
        if: ${{ !contains(env.VERSION, 'b') && !contains(env.VERSION, 'rc') }}
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: chart
          target_dir: chart
          chart_version: ${{ env.VERSION }}
